# Mapeamento de tradução de etiquetas
traducao_etiquetas = {
    'person': 'pessoa',
    'cup': 'xícara ou copo',
    'wine glass': 'taça de vinho',
    'bowl': 'tigela',
    'spoon': 'colher',
    'apple': 'maçã',
    'vase': 'vaso',
    'chair': 'cadeira',
    'refrigerator': 'refrigerador',
    'microwave': 'microondas',
    'potted plant': 'vaso com planta',
    'couch': 'sofá',
    'dining table': 'mesa de jantar',
    'dog': 'cachorro',
    'cat': 'gato',
    'bird': 'passáro',
    'motorcycle': 'motocicleta',
    'bus': 'ônibus',
    'car': 'carro',
    'umbrella': 'guarda-chuva',
    'truck': 'caminhão',
    'traffic light': 'semáforo',
    'backpack': 'mochila',
    'handbag': 'Bolsa',
    'knife': 'faca',
    'fork': 'garfo',
    'bottle': 'garrafa',
    'cell phone': 'celular ou controle remoto',
    'bed': 'cama',
    'toilet': 'vaso sanitário',
    'sink': 'pia',
    'remote': 'controle remoto ou celular',
    'sports car': 'carro esportivo',
    'bicycle': 'bicicleta',
    'airplane': 'avião',
    'boat': 'barco',
    'train': 'trem',
    'horse': 'cavalo',
    'elephant': 'elefante',
    'bear': 'urso',
    'table': 'mesa',
    'sofa': 'sofá',
    'television': 'TV',
    'laptop': 'laptop',
    'mouse': 'mouse',
    'keyboard': 'teclado',
    'book': 'livro',
    'toaster': 'torradeira',
    'toilet paper': 'papel higiênico',
    'tv monitor': 'monitor de TV',
    'suitcase': 'mala',
    'tennis racket': 'raquete de tênis',
    'baseball bat': 'bastão de beisebol',
    'baseball glove': 'luva de beisebol',
    'skateboard': 'skate',
    'surfboard': 'prancha de surfe',
    'tennis ball': 'bola de tênis',
    'frisbee': 'disco',
    'kite': 'pipa',
    'guitar': 'guitarra',
    'trumpet': 'trompete',
    'piano': 'piano',
    'hair drier': 'secador de cabelo',
    'scissors': 'tesoura',
    'pen': 'caneta'
    # Adicione mais traduções conforme necessário
}
